import { ToDoItem } from "./to-do-item-class";

export const completedItems: ToDoItem[] = [

{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },

{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },
{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },
{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },
{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },
{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },
{title: "title",
priority: "High",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 20,
completed: false},

{title: "title",
priority: "Medium",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 10,
completed: false },

{title: "title",
priority: "Low",
content: "lorem Ipsem sdk;fjasdf;las",
due: true,
dueDate: new Date(2, 30, 2030),
pointVal: 5,
completed: false },



];